channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=21.3.1
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - typing-extensions==4.6.3
  
  - azureml-core==1.38.0
  - azureml-defaults==1.38.0
  - azureml-contrib-services==1.38.0
  - azureml-inference-server-http==1.1.0
  - azureml-ai-monitoring==1.0.0
  
name: mlflow-env
